name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - codespell
  - types-decorator
  - mypy
  - numpy==2.1.0
  - pytest
  - matplotlib>=3.10.0
  - ruff

  - numpydoc>=1.8.0
  - sphinx>=5.1.0

  # Stubs
  - scipy-stubs
