name: lint
channels:
  - conda-forge
  - defaults
dependencies:
  # required
  - pip
  - bandit
  - codespell
  - types-decorator
  - mypy
  - numpy==2.1.0
  - pytest
  - matplotlib>=3.10.0
  - ruff

  # Dependencies for velin
  - numpydoc>=1.1.0
  - sphinx>=5.1.0
  - pygments
  - black

  # Stubs
  - scipy-stubs

  - pip:
    - velin
