[build-system]
requires = [
    "setuptools >= 48",
    "wheel >= 0.29.0",
]
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
markers = [
    "network: marks tests that require network access"
]
