from _typeshed import Incomplete

def salience(S, *, freqs, harmonics, weights: Incomplete | None = ..., aggregate: Incomplete | None = ..., filter_peaks: bool = ..., fill_value=..., kind: str = ..., axis: int = ...): ...
def interp_harmonics(x, *, freqs, harmonics, kind: str = ..., fill_value: int = ..., axis: int = ...): ...
