def thaat_to_degrees(thaat): ...
def mela_to_degrees(mela): ...
def mela_to_svara(mela, *, abbr: bool = ..., unicode: bool = ...): ...
def list_mela(): ...
def list_thaat(): ...
def key_to_notes(key, *, unicode: bool = ...): ...
def key_to_degrees(key): ...
