from _typeshed import Incomplete

def estimate_tuning(*, y: Incomplete | None = ..., sr: int = ..., S: Incomplete | None = ..., n_fft: int = ..., resolution: float = ..., bins_per_octave: int = ..., **kwargs): ...
def pitch_tuning(frequencies, *, resolution: float = ..., bins_per_octave: int = ...): ...
def piptrack(*, y: Incomplete | None = ..., sr: int = ..., S: Incomplete | None = ..., n_fft: int = ..., hop_length: Incomplete | None = ..., fmin: float = ..., fmax: float = ..., threshold: float = ..., win_length: Incomplete | None = ..., window: str = ..., center: bool = ..., pad_mode: str = ..., ref: Incomplete | None = ...): ...
def yin(y, *, fmin, fmax, sr: int = ..., frame_length: int = ..., win_length: Incomplete | None = ..., hop_length: Incomplete | None = ..., trough_threshold: float = ..., center: bool = ..., pad_mode: str = ...): ...
def pyin(y, *, fmin, fmax, sr: int = ..., frame_length: int = ..., win_length: Incomplete | None = ..., hop_length: Incomplete | None = ..., n_thresholds: int = ..., beta_parameters=..., boltzmann_parameter: int = ..., resolution: float = ..., max_transition_rate: float = ..., switch_prob: float = ..., no_trough_prob: float = ..., fill_na=..., center: bool = ..., pad_mode: str = ...): ...
