from _typeshed import Incomplete

def moved(*, moved_from, version, version_removed): ...
def deprecated(*, version, version_removed): ...
def vectorize(*, otypes: Incomplete | None = ..., doc: Incomplete | None = ..., excluded: Incomplete | None = ..., cache: bool = ..., signature: Incomplete | None = ...): ...
