from _typeshed import Incomplete

def example(key, *, hq: bool = ...): ...
ex = example

def list_examples() -> None: ...
def example_info(key) -> None: ...
def find_files(directory, *, ext: Incomplete | None = ..., recurse: bool = ..., case_sensitive: bool = ..., limit: Incomplete | None = ..., offset: int = ...): ...
