from _typeshed import Incomplete

def mel_to_stft(M, *, sr: int = ..., n_fft: int = ..., power: float = ..., **kwargs): ...
def mel_to_audio(M, *, sr: int = ..., n_fft: int = ..., hop_length: Incomplete | None = ..., win_length: Incomplete | None = ..., window: str = ..., center: bool = ..., pad_mode: str = ..., power: float = ..., n_iter: int = ..., length: Incomplete | None = ..., dtype=..., **kwargs): ...
def mfcc_to_mel(mfcc, *, n_mels: int = ..., dct_type: int = ..., norm: str = ..., ref: float = ..., lifter: int = ...): ...
def mfcc_to_audio(mfcc, *, n_mels: int = ..., dct_type: int = ..., norm: str = ..., ref: float = ..., lifter: int = ..., **kwargs): ...
