from _typeshed import Incomplete

def tempogram(*, y: Incomplete | None = ..., sr: int = ..., onset_envelope: Incomplete | None = ..., hop_length: int = ..., win_length: int = ..., center: bool = ..., window: str = ..., norm=...): ...
def fourier_tempogram(*, y: Incomplete | None = ..., sr: int = ..., onset_envelope: Incomplete | None = ..., hop_length: int = ..., win_length: int = ..., center: bool = ..., window: str = ...): ...
