from _typeshed import Incomplete

class CacheManager:
    memory: Incomplete
    level: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def __call__(self, level): ...
    def clear(self, *args, **kwargs): ...
    def eval(self, *args, **kwargs): ...
    def format(self, *args, **kwargs): ...
    def reduce_size(self, *args, **kwargs): ...
    def warn(self, *args, **kwargs): ...

cache: Incomplete
