from _typeshed import Incomplete

def beat_track(*, y: Incomplete | None = ..., sr: int = ..., onset_envelope: Incomplete | None = ..., hop_length: int = ..., start_bpm: float = ..., tightness: int = ..., trim: bool = ..., bpm: Incomplete | None = ..., prior: Incomplete | None = ..., units: str = ...): ...
def tempo(*, y: Incomplete | None = ..., sr: int = ..., onset_envelope: Incomplete | None = ..., hop_length: int = ..., start_bpm: int = ..., std_bpm: float = ..., ac_size: float = ..., max_tempo: float = ..., aggregate=..., prior: Incomplete | None = ...): ...
def plp(*, y: Incomplete | None = ..., sr: int = ..., onset_envelope: Incomplete | None = ..., hop_length: int = ..., win_length: int = ..., tempo_min: int = ..., tempo_max: int = ..., prior: Incomplete | None = ...): ...
