from _typeshed import Incomplete

def decompose(S, *, n_components: Incomplete | None = ..., transformer: Incomplete | None = ..., sort: bool = ..., fit: bool = ..., **kwargs): ...
def hpss(S, *, kernel_size: int = ..., power: float = ..., mask: bool = ..., margin: float = ...): ...
def nn_filter(S, *, rec: Incomplete | None = ..., aggregate: Incomplete | None = ..., axis: int = ..., **kwargs): ...
