def hpss(y, **kwargs): ...
def harmonic(y, **kwargs): ...
def percussive(y, **kwargs): ...
def time_stretch(y, *, rate, **kwargs): ...
def pitch_shift(y, *, sr, n_steps, bins_per_octave: int = ..., res_type: str = ..., **kwargs): ...
def remix(y, intervals, *, align_zeros: bool = ...): ...
def trim(y, *, top_db: int = ..., ref=..., frame_length: int = ..., hop_length: int = ..., aggregate=...): ...
def split(y, *, top_db: int = ..., ref=..., frame_length: int = ..., hop_length: int = ..., aggregate=...): ...
