from _typeshed import Incomplete

def onset_detect(*, y: Incomplete | None = ..., sr: int = ..., onset_envelope: Incomplete | None = ..., hop_length: int = ..., backtrack: bool = ..., energy: Incomplete | None = ..., units: str = ..., normalize: bool = ..., **kwargs): ...
def onset_strength(*, y: Incomplete | None = ..., sr: int = ..., S: Incomplete | None = ..., lag: int = ..., max_size: int = ..., ref: Incomplete | None = ..., detrend: bool = ..., center: bool = ..., feature: Incomplete | None = ..., aggregate: Incomplete | None = ..., **kwargs): ...
def onset_backtrack(events, energy): ...
def onset_strength_multi(*, y: Incomplete | None = ..., sr: int = ..., S: Incomplete | None = ..., n_fft: int = ..., hop_length: int = ..., lag: int = ..., max_size: int = ..., ref: Incomplete | None = ..., detrend: bool = ..., center: bool = ..., feature: Incomplete | None = ..., aggregate: Incomplete | None = ..., channels: Incomplete | None = ..., **kwargs): ...
