name: CI Docs

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: True


env:
  LIBROSA_DOC_DEBUG: True  # Disable docstring example execution

jobs:
    setup:
        name: "Doc environment setup"
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                include:
                    - os: ubuntu-latest
                      python-version: "3.12"
                      channel-priority: "flexible"
                      envfile: ".github/environment-docs.yml"
        steps:
        - uses: actions/checkout@v7
          with:
            fetch-depth: 0

        - name: Setup Miniforge
          uses: conda-incubator/setup-miniconda@v4
          with:
            miniforge-version: latest
            activate-environment: docs
            conda-remove-defaults: true
            python-version: ${{ matrix.python-version }}

        - name: Get Date
          id: get-date
          run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
          shell: bash

        - name: Cache Conda env
          uses: actions/cache@v6
          with:
            path: ${{ env.CONDA }}/envs
            key:
              conda-${{ runner.os }}--${{ runner.arch }}--${{
              steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER
              }}-${{ matrix.python-version }}-${{ hashFiles( matrix.envfile ) }}
          env:
            CACHE_NUMBER: 0
          id: cache

        - name: Update environment
          run:
            mamba env update -n docs -f ${{ matrix.envfile }} 
          if: steps.cache.outputs.cache-hit != 'true'

        - name: Conda info
          shell: bash -l {0}
          run: |
            conda info -a
            conda list

        - name: Install librosa
          shell: bash -l {0}
          run: python -m pip install --upgrade-strategy only-if-needed -e .[docs]

        #- name: Build multi-version site
        #  shell: bash -l {0}
        #  run: |
        #    sphinx-multiversion -D smv_latest_version=$(./scripts/get_latest_release.sh) docs build/html
        #    touch build/html/.nojekyll
        #    cp docs/docsite-index-redirect.html build/html/index.html
        #    ln -srf build/html/$(./scripts/get_latest_release.sh) build/html/latest  # auto-link the latest tag
        - name: Build documentation site
          shell: bash -l {0}
          run: |
            sphinx-build -b html docs build/html
            touch build/html/.nojekyll
            cp docs/docsite-index-redirect.html build/html/index.html

        - name: Upload compiled documentation site
          if: github.event_name == 'pull_request'
          uses: actions/upload-artifact@v7
          with:
            name: librosa-docs-pr-${{ github.event.pull_request.number }}
            path: build/html
            retention-days: 7
            overwrite: true
            include-hidden-files: true

        - name: Link checking
          id: linkcheck
          shell: bash -l {0}
          working-directory: docs
          run: make linkcheck

        - name: Check for broken links
          shell: bash -l {0}
          run: |
            if [[ -n "$(find build/html/ -type l ! -exec test -e {} \; -print -quit)" ]]; then false; fi
