name: Docs

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build Release Asset"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc:
    name: "Documentation build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          python-version: "3.12"
          add-pip-as-python-dependency: true
          auto-activate-base: false
          activate-environment: docs
          channel-priority: flexible
          environment-file: .github/environment-docs.yml

      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info -a
          conda list

      - name: Install librosa
        shell: bash -el {0}
        run: python -m pip install --upgrade-strategy only-if-needed -e .[docs]

      - name: Build documentations
        shell: bash -el {0}
        run: |
          sphinx-build -b html docs build/html/dev
          cp docs/docsite-index-redirect.html build/html/index.html

      - name : Pull historical documentation assets
        shell: bash -el {0}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSIONS=$(gh release list -O asc --exclude-drafts --exclude-pre-releases --json tagName --jq '.[].tagName')

          PUSHED_VERSIONS=""
          for ver in $VERSIONS; do
            echo "Fetching docs for $ver"
            mkdir -p "build/html/$ver"
            if gh release download "$ver" --pattern "librosa-docs.zip" --dir "temp_dl"; then
              unzip -q "temp_dl/librosa-docs.zip" -d "build/html/$ver"
              rm -rf temp_dl
              LATEST=$ver
              PUSHED_VERSIONS="$ver $PUSHED_VERSIONS"
            else
              echo "No docs found for $ver; skipping."
              rmdir "build/html/$ver"
            fi
          done
          ln -srf build/html/$LATEST build/html/latest
          ln -srf build/html/dev build/html/main
          python docs/create_version_index.py --preferred $LATEST dev $PUSHED_VERSIONS

      - name: Push to web
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DOC_PUBLISH_TOKEN }}
          external_repository: librosa/web-staging
          enable_jekyll: false
          publish_branch: main
          publish_dir: build/html
          user_name: librosa
          user_email: brian.mcfee@nyu.edu
          force_orphan: true
